name: Build Test

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Test
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: %LOCALAPPDATA%/electron/Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Cache Electron-Builder
        uses: actions/cache@v3
        with:
          path: %LOCALAPPDATA%/electron-builder/Cache
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: Build Electron App
        run: |
          npm install -g yarn
          yarn install
          yarn build:electron
        env:
          github_token: ${{ secrets.github_token }}

      - name: Upload Asar To Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app.asar
          path: |
            release/win-unpacked/resources/app.asar